# Generated by Django 2.0.3 on 2018-04-11 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180410_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
    ]
